---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2022-02-24T17:08:46.988715405+02:00"
  name: pythonapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: pythonapp-latest
  suspend: true

