apiVersion: v1
kind: Service
metadata:
    name: "randaks-77e9"
    labels:
        app: "randaks-77e9"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "randaks-77e9"